_("Windows");
_("Watch");
_("Call Stack");
_("Debug Output");
_("Start Debugging");
_("Start Debugging");
_("Break");
_("Break");
_("Stop Debugging");
_("Stop Debugging");
_("Step");
_("Step");
_("Step Over");
_("Step Over");
_("Step Out");
_("Step Out");
_("Find Replace");
_("&Find text:");
_("Re&place with:");
_("Options");
_("Match &case");
_("Match &whole");
_("Search &up");
_("Regular &expressions");
_("Find in");
_("Current &document");
_("All &open document");
_("Find &Next");
_("&Replace");
_("Replace&All");
_("&Mark All");
_("Cancel");
_("Up");
_("Up");
_("Go Up");
_("Refresh");
_("Refresh");
_("Chage View");
_("Chage View");
_(" URL : ");
_("&File");
_("&New");
_("Create a new file");
_("&Open");
_("Open a file");
_("&Close");
_("Close the active file");
_("&Save");
_("Save selected file");
_("&Save all");
_("Save all modified files");
_("R&ecent files");
_("Open a recent file");
_("&Clear history");
_("Clear the recent files list");
_("&Quit");
_("Exit");
_("&Edit");
_("&Undo");
_("Undo the last editing operation");
_("&Redo");
_("Redo the last editing operation");
_("Cu&t");
_("Copy selected text to clipboard and erase it");
_("&Copy");
_("Copy selected text to clipboard");
_("&Paste");
_("Paste text from clipboard");
_("&Select all");
_("Save all modified files");
_("&Find ...");
_("Find or replace text");
_("F&ind in file...");
_("Find or replace text in files");
_("&Goto...");
_("Goto line");
_("&Highlight mode");
_("Plain Text");
_("&Bookmarks");
_("&View");
_("&Explorer");
_("Show/hide explorer");
_("Toolbars");
_("&Main Toolbar");
_("Show/hide main toolbar");
_("&Full Screen Toolbar");
_("Show/hide full screen toolbar");
_("F&ull Screen");
_("Switch to FullScreen view");
_("&Tools");
_("P&lugins");
_("Manage &plugins...");
_("Enable or disable plugins for the next session");
_("&Settings");
_("&Environment...");
_("Change environment settings");
_("E&ditor...");
_("Change editor's settings");
_("&Compiler and debugger...");
_("Change compiler and debugger settings");
_("&Global variables...");
_("Change global compiler variables");
_("&Scripting...");
_("Change scripting settings");
_("&Help");
_("&About...");
_("About Code::Blocks");
_("&Tips");
_("Tips on using Code::Blocks");
_("&Plugins");
_("Create New ...");
_("&OK");
_("&Cancel");
